package:
  name: fsttrpgtables
  version: 0.2.1

build:
 number: 1
 string: alpha

source:
  git_url: https://github.com/Krypticdator/FSTTRPGTables.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
about:
  summary: Fuzion Roleplayin System static tables package